# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(buildversion)

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: TfxInstaller@2
  inputs:
    version: 'v0.6.x'
- task: PackageAzureDevOpsExtension@2
  inputs:
    rootFolder: 'azuredevops/powerbiactions'
    outputVariable: 'ExOutputPath'
    publisherId: 'maikvandergaag'
    extensionTag: 'alpha'
    extensionVersion: '$(Build.Buildnumber)'
    updateTasksVersion: true
    extensionVisibility: 'private'
    extensionPricing: 'free'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: powerbiactions'
  inputs:
    PathtoPublish: '$(ExOutputPath)'
    ArtifactName: arm-ttk

- task: versioncounter@1
  displayName: 'Version number counter'
  inputs:
    VersionVariable: buildversion
    UpdateMinorVersion: true
    MaxValuePatchVersion: 9
    UpdateMajorVersion: true
    MaxValueMinorVersion: 9
    DevOpsPat: '$(devops-pat-versionnumber)'